package ca.rest.domain;

import javax.persistence.*;

@Entity
@Table( name = "blog") // needed if table name is different from class name
public class Blog {
    @Id //specifies that this is a primary key
    @GeneratedValue(strategy = GenerationType.AUTO) //specifies that this will be auto-generated by the database
    private int id;
    @Column( name = "title") //needed if column name is different than attribute name
    private String title;

    @Column(nullable = true)
    private String content;

    public Blog() {  }

    public Blog(String title, String content) {
        this.setTitle(title);
        this.setContent(content);
    }

    public Blog(int id, String title, String content) {
        this.setId(id);
        this.setTitle(title);
        this.setContent(content);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String toString() {
        return "Blog{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}
